const categories = {
    electronics: [
      'electronics',
      'tv',
      'television',
      'computer',
      'laptop',
      'camera',
      'phone',
      'smartphone',
      'tablet',
      'headphones',
      'speaker',
      'gadget',
      'audio',
      'video',
      'gaming',
      'accessories',
      'wireless',
      'tech',
    ],
    home: [
      'home',
      'furniture',
      'kitchen',
      'bedroom',
      'bathroom',
      'living room',
      'dining room',
      'home decor',
      'lighting',
      'appliances',
      'home improvement',
      'bedding',
      'storage',
      'organizer',
      'cleaning',
      'utensils',
      'cookware',
      'décor',
    ],
    clothing: [
      'clothing',
      'apparel',
      'fashion',
      'clothes',
      'shoes',
      'footwear',
      'accessories',
      'jewelry',
      'bags',
      'dresses',
      't-shirts',
      'pants',
      'sweaters',
      'hoodies',
      'activewear',
      'lingerie',
      'outerwear',
    ],
    beauty: [
      'beauty',
      'skincare',
      'makeup',
      'cosmetics',
      'hair',
      'fragrance',
      'perfume',
      'nail care',
      'beauty tools',
      'beauty accessories',
      'self-care',
      'bath',
      'body',
      'spa',
      'wellness',
      'anti-aging',
      'clean beauty',
      'natural',
    ],
    sports: [
      'sports',
      'outdoors',
      'fitness',
      'exercise',
      'equipment',
      'athletic',
      'sports apparel',
      'workout',
      'running',
      'yoga',
      'cycling',
      'hiking',
      'swimming',
      'team sports',
      'gym',
      'training',
    ],
    books: [
      'books',
      'literature',
      'novel',
      'magazine',
      'educational',
      'non-fiction',
      'fiction',
      'biography',
      'self-help',
      'reference',
      'cookbooks',
      'history',
      'mystery',
      'science fiction',
      'fantasy',
      'poetry',
      'business',
      'travel',
    ],
    toys: [
      'toys',
      'games',
      'play',
      'kids',
      'children',
      'educational toys',
      'puzzles',
      'building blocks',
      'dolls',
      'action figures',
      'board games',
      'arts and crafts',
      'outdoor play',
      'pretend play',
      'STEM toys',
      'remote control',
      'vehicles',
    ],
    automotive: [
      'automotive',
      'car',
      'vehicle',
      'parts',
      'accessories',
      'auto maintenance',
      'tires',
      'car care',
      'car electronics',
      'car interior',
      'car exterior',
      'tools',
      'motorcycle',
      'truck',
      'off-road',
      'performance',
      'safety',
    ],
    groceries: [
      'groceries',
      'food',
      'beverages',
      'snacks',
      'pantry',
      'grocery items',
      'canned goods',
      'beverages',
      'snack foods',
      'baking supplies',
      'condiments',
      'dairy',
      'fresh produce',
      'frozen foods',
      'breakfast',
      'sweets',
      'health foods',
    ],
    // Add more categories as needed
  };

  module.exports = categories